# Generated by Django 5.0 on 2023-12-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=360)),
                ('like', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
