# Generated by Django 5.0 on 2023-12-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
